title: "iHDI: Interdisciplinary Workshop on Human-Drone Interaction"
subtitle: at CHI 2020, Honolulu, Hawai ªi, USA
logo: img/avatar.png
avatar: img/avatar.png
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
baseurl: "/"
url: ""
